services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: taskfusion
      POSTGRES_USER: taskfusion
      POSTGRES_PASSWORD: supersecret
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  auth:
    build: ./auth-service
    restart: always
    networks:
      - backend
    depends_on:
      - db

  project-management:
    build: ./project-management-service
    restart: always
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/taskfusion"
      DATABASE_USERNAME: taskfusion
      DATABASE_PASSWORD: supersecret
    networks:
      - backend
    depends_on:
      - auth

  task-management:
    build: ./task-management-service
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432  
      DB_DATABASE: taskfusion  
      DB_USERNAME: taskfusion 
      DB_PASSWORD: supersecret
    networks:
      - backend
    depends_on:
      - auth

  notification-service:
    build: ./notification-service
    restart: always
    environment:
      KAFKA_BROKER: <<kafkaip>>
    depends_on:
      - auth
    networks:
      - backend

  main-api:
    build: ./main-api
    restart: always
    depends_on:
      - auth
    env_file:
      - ./main-api/.env
    networks:
      - backend
    ports:
      - "80:80"

networks:
  backend:
    driver: bridge

volumes:
  db-data:
