services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: taskfusion
      POSTGRES_USER: taskfusion
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    networks:
      - backend

  auth:
    build: ./auth-service
    restart: always
    ports:
      - "5003:3000"
    networks:
      - backend
    depends_on:
      - db

  project-management:
    build: ./project-management-service
    restart: always
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/taskfusion"
      DATABASE_USERNAME: taskfusion
      DATABASE_PASSWORD: supersecret
    ports: 
      - "5002:8011"
    networks:
      - backend
    depends_on:
      - auth

  task-management:
    build: ./task-management-service
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432  
      DB_DATABASE: taskfusion  
      DB_USERNAME: taskfusion 
      DB_PASSWORD: supersecret
    ports: 
      - "5004:8080"
    networks:
      - backend
    depends_on:
      - auth

  notification-service:
    build: ./notification-service
    restart: always
    environment:
      KAFKA_BROKER: <<secret>>
    depends_on:
      - auth
    ports:
      - "5001:5001"
    networks:
      - backend

  main-api:
    build: ./main-api
    restart: always
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

