name: task_management_service
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dotenv: ^4.2.0
  postgres: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
