services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: taskfusion
      POSTGRES_USER: taskfusion
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    networks:
      - backend

  auth:
    build: .
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge
